<?php
/* xoops_version.php 2006-11-04 10:56:12
   WoW Roster X - WoW Roster for Xoops - A XOOPS CMS Module
   Copyright (c) 2006 Mike DeShane, US
   URL:     www.pkcomp.net
   Contact: mdeshane@pkcomp.net

   XOOPS
   Copyright (c) 2000 XOOPS.org
   URL:     https://www.xoops.org/

   This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 */

//The next comment block is for PHPDocumentor
/**
 * WoW Roster X - WoW Roster for Xoops
 *
 * This file conforms to the Xoops standard for the xoops_version.php file. Constant declarations beginning _MI_ are contained in language/../modinfo.php
 *
 * @author Mike DeShane (mdeshane@pkcomp.net)
 * @copyright 2006 Mike DeShane, US
 */
global $modversion;

$modversion['name'] = _MI_WRX_NAME;
$modversion['version'] = 1.25;
$modversion['description'] = _MI_WRX_DESC;
$modversion['credits'] = 'Mike DeShane - http://www.pkcomp.net';
$modversion['author'] = 'Mike DeShane';
$modversion['help'] = 'wrx_help.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'img/wrx_slogo.png';
$modversion['dirname'] = 'wowrosterx';
$modversion['onUpdate'] = 'install_funcs.php';
$modversion['onInstall'] = 'install_funcs.php';
$modversion['onUninstall'] = 'install_funcs.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/wrx_mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'wrx_roster_account';
$modversion['tables'][1] = 'wrx_roster_buffs';
$modversion['tables'][2] = 'wrx_roster_config';
$modversion['tables'][3] = 'wrx_roster_guild';
$modversion['tables'][4] = 'wrx_roster_items';
$modversion['tables'][5] = 'wrx_roster_mailbox';
$modversion['tables'][6] = 'wrx_roster_members';
$modversion['tables'][7] = 'wrx_roster_memberlog';
$modversion['tables'][8] = 'wrx_roster_pets';
$modversion['tables'][9] = 'wrx_roster_players';
$modversion['tables'][10] = 'wrx_roster_pvp2';
$modversion['tables'][11] = 'wrx_roster_quests';
$modversion['tables'][12] = 'wrx_roster_realmstatus';
$modversion['tables'][13] = 'wrx_roster_recipes';
$modversion['tables'][14] = 'wrx_roster_reputation';
$modversion['tables'][15] = 'wrx_roster_skills';
$modversion['tables'][16] = 'wrx_roster_spellbook';
$modversion['tables'][17] = 'wrx_roster_spellbooktree';
$modversion['tables'][18] = 'wrx_roster_talents';
$modversion['tables'][19] = 'wrx_roster_talenttree';

// Main Menu
$modversion['hasMain'] = 1;
$modversion['sub'][0]['name'] = _MI_WRX_UMNAME0;
$modversion['sub'][0]['url'] = 'index.php';
$modversion['sub'][1]['name'] = _MI_WRX_UMNAME1;
$modversion['sub'][1]['url'] = 'guildinfo.php';
$modversion['sub'][2]['name'] = _MI_WRX_UMNAME2;
$modversion['sub'][2]['url'] = 'indexstat.php';
$modversion['sub'][3]['name'] = _MI_WRX_UMNAME3;
$modversion['sub'][3]['url'] = 'tradeskills.php';
$modversion['sub'][4]['name'] = _MI_WRX_UMNAME4;
$modversion['sub'][4]['url'] = 'guildbank.php';
$modversion['sub'][5]['name'] = _MI_WRX_UMNAME5;
$modversion['sub'][5]['url'] = 'indexpvp.php';
$modversion['sub'][6]['name'] = _MI_WRX_UMNAME6;
$modversion['sub'][6]['url'] = 'indexhonor.php';
$modversion['sub'][7]['name'] = _MI_WRX_UMNAME7;
$modversion['sub'][7]['url'] = 'memberlog.php';
$modversion['sub'][8]['name'] = _MI_WRX_UMNAME8;
$modversion['sub'][8]['url'] = 'indexinst.php';
$modversion['sub'][9]['name'] = _MI_WRX_UMNAME9;
$modversion['sub'][9]['url'] = 'update.php';
$modversion['sub'][10]['name'] = _MI_WRX_UMNAME10;
$modversion['sub'][10]['url'] = 'indexsearch.php';
$modversion['sub'][11]['name'] = _MI_WRX_UMNAME11;
$modversion['sub'][11]['url'] = 'indexquests.php';

// Admin menu things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin.php';
$modversion['adminmenu'] = 'admin/menu.inc';

// Blocks ** The Blocks will hopefully be useable in the Final version **
//$modversion['blocks'][0]['name'] = _MI_WRX_BLKNAME0;
//$modversion['blocks'][0]['description'] = _MI_WRX_BLKDESC0;
//$modversion['blocks'][0]['file'] = 'block_wrx_motd.php';
//$modversion['blocks'][0]['show_func'] = 'b_wrx_block0_show';
//$modversion['blocks'][0]['edit_func'] = 'b_wrx_block0_edit';
//$modversion['blocks'][0]['template'] = 'b_wrx_motd.tpl';
//$modversion['blocks'][0]['options'] = '';
//$modversion['blocks'][1]['name'] = _MI_WRX_BLKNAME1;
//$modversion['blocks'][1]['description'] = _MI_WRX_BLKDESC1;
//$modversion['blocks'][1]['file'] = 'block_wrx_realm.php';
//$modversion['blocks'][1]['show_func'] = 'b_wrx_block1_show';
//$modversion['blocks'][1]['edit_func'] = 'b_wrx_block1_edit';
//$modversion['blocks'][1]['template'] = 'b_wrx_realm.tpl';
//$modversion['blocks'][1]['options'] = '';

// Search things
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'lib/search.inc';
$modversion['search']['func'] = 'wrx_search';

// Comment things
$modversion['hasComments'] = 0;
$modversion['comments']['itemName'] = '';
$modversion['comments']['pageName'] = '';
$modversion['comments']['extraParams'] = null;
$modversion['comments']['callbackFile'] = 'lib/comments.inc';
$modversion['comments']['callback']['approve'] = 'wrx_com_approve';
$modversion['comments']['callback']['update'] = 'wrx_com_update';

// Notification things
$modversion['hasNotification'] = 0;
$modversion['notification']['lookup_file'] = 'lib/notification.inc';
$modversion['notification']['lookup_func'] = 'wrx_notify_iteminfo';
/**
 * You need to add notification category and event information here
 */

/*
 * This file was generated by XBS ModGen, (c) 2006 A Kitson, UK. See http://xoobs.net
 * ModGen is a Module Code Generator for the Xoops CMS.  See http://xoops.org
 */
