<?php
/* admin2.php 2006-11-04 10:56:12
   WoW Roster X - WoW Roster for Xoops - A XOOPS CMS Module
   Copyright (c) 2006 Mike DeShane, US
   URL:     www.pkcomp.net
   Contact: mdeshane@pkcomp.net

   XOOPS
   Copyright (c) 2000 XOOPS.org
   URL:     https://www.xoops.org/

   This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 */

//The next comment block is for PHPDocumentor
/**
 * WoW Roster X - WoW Roster for Xoops
 *
 * Module administration language constant definitions
 *
 * @author Mike DeShane (mdeshane@pkcomp.net)
 * @copyright 2006 Mike DeShane, US
 */

/*
 * This file is required only for Xoops <2.2  At 2.2 facilities will exist to
 * have a site wide administration menu that will supercede the need for this file
 */

/**#@+
 * Module Admin global menu definitions
 */
define('_AD_MODADMIN', 'Administration');
define('_AD_MOD_CONFIG', 'Module Config');
define('_AD_MOD_HOME', 'Module Home Page');
define('_AD_DOCS', 'Module Documentation');
define('_AD_SUPPORT', 'Module Support');
define('_AD_DONATIONS', 'Module Donations');
/**#@-*/

/*
 * This file was generated by XBS ModGen, (c) 2006 A Kitson, UK. See http://xoobs.net
 * ModGen is a Module Code Generator for the Xoops CMS.  See http://xoops.org
 */
