<?php
/* admin.php 2006-11-04 10:56:12
   WoW Roster X - WoW Roster for Xoops - A XOOPS CMS Module
   Copyright (c) 2006 Mike DeShane, US
   URL:     www.pkcomp.net
   Contact: mdeshane@pkcomp.net

   XOOPS
   Copyright (c) 2000 XOOPS.org
   URL:     https://www.xoops.org/

   This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 */

//The next comment block is for PHPDocumentor
/**
 * WoW Roster X - WoW Roster for Xoops
 *
 * Module administration non language and language constant definitions
 *
 * @author Mike DeShane (mdeshane@pkcomp.net)
 * @copyright 2006 Mike DeShane, US
 */

/**#@+
 * Constants for Admin menu - non language specific
 */

/**
 * Admin menu parameters
 *
 * These MUST follow the format _AM_<ModDir>_URL_DOCS etc
 * so that the xoops_module_admin_header functions can work.
 * The suffix after <ModDir> is not optional!
 * Leave them commented out if you do not have the functionality for your module
 *
 * Relative url from module directory for documentation
 */
define('_AM_WOWROSTERX_URL_DOCS', 'admin/help.php');
/**
 * Absolute url for module support site
 */
define('_AM_WOWROSTERX_URL_SUPPORT', 'http://www.pkcomp.net');
/**
 * absolute url for module donations site
 */
//define("_AM_WOWROSTERX_URL_DONATIONS","");

/**
 * Module configuration option - MUST follow the format _AM_<ModDir>_MODCONFIG
 * Value MUST be "xoops", "module" or "none"
 */
define('_AM_WOWROSTERX_MODCONFIG', 'module');

/**
 * If module configuration option = "module" then define the name of the script
 * to call for module configuration.  This relative to modDir/admin/
 * MUST follow the format _AM_<ModDir>_MODCONFIGURL
 * e.g. define("_AM_WOWROSTERX_MODCONFIGURL","wrx_config.inc");
 * and define a message that is shown to users prior to redirecting to the config page
 * e.g. define("_AM_WOWROSTERX_MODCONFIGREDIRECT","Configuration is done via the CDM system. You will shortly be redirected there.")
 */
/**#@-*/

/**#@+
 * Constants for Admin menus - Language specific
 */

// Admin menu breadcrumb
define('_AM_WRX_ADMENU0', 'Roster Config');
define('_AM_WRX_ADMENU1', 'Uplaod Profile');

//buttons
define('_AM_WRX_INSERT', 'Insert');
define('_AM_WRX_BROWSE', 'Browse');
define('_AM_WRX_SUBMIT', 'Submit');
define('_AM_WRX_SAVE', 'Save');
define('_AM_WRX_CANCEL', 'Cancel');
define('_AM_WRX_RESET', 'Reset');
define('_AM_WRX_EDIT', 'Edit');
define('_AM_WRX_GO', 'Go');
define('_AM_WRX_DEL', 'Delete');
define('_AM_WRX_USE', 'Use This Record');

//button labels
define('_AM_WRX_INSERT_DESC', 'Create a new record');
define('_AM_WRX_BUTTONTRAY', 'Click to perform action');

//Error messages

//Other messages

//Form Labels

/**#@-*/

/*
 * This file was generated by XBS ModGen, (c) 2006 A Kitson, UK. See http://xoobs.net
 * ModGen is a Module Code Generator for the Xoops CMS.  See http://xoops.org
 */
