<?php
/* main.php 2006-11-04 10:56:12
   WoW Roster X - WoW Roster for Xoops - A XOOPS CMS Module
   Copyright (c) 2006 Mike DeShane, US
   URL:     www.pkcomp.net
   Contact: mdeshane@pkcomp.net

   XOOPS
   Copyright (c) 2000 XOOPS.org
   URL:     https://www.xoops.org/

   This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 */

//The next comment block is for PHPDocumentor
/**
 * WoW Roster X - WoW Roster for Xoops
 *
 *
 *
 * @author Mike DeShane (mdeshane@pkcomp.net)
 * @copyright 2006 Mike DeShane, US
 */

/**
 * Constant definitions that are language specific rather than module specific
 * Definitions contained in this file conform to the Xoops standard for Language main.php file format
 * Typically your user side screen messages are put in this file
 */

/**#@+
 * Language specific definitions
 */

//Message Constants
define('_MD_WRX_PAGETITLE', 'Page title for %s - %s');
define('_MD_WRX_MSG1', 'Please edit %s to display your information for this page');

// Error string constants
define('_MD_WRX_ERR_1', 'Example error message');

/**#@-*/

/*
 * This file was generated by XBS ModGen, (c) 2006 A Kitson, UK. See http://xoobs.net
 * ModGen is a Module Code Generator for the Xoops CMS.  See http://xoops.org
 */
