<?php
/* modinfo.php 2006-11-04 10:56:12
   WoW Roster X - WoW Roster for Xoops - A XOOPS CMS Module
   Copyright (c) 2006 Mike DeShane, US
   URL:     www.pkcomp.net
   Contact: mdeshane@pkcomp.net

   XOOPS
   Copyright (c) 2000 XOOPS.org
   URL:     https://www.xoops.org/

   This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 */

//The next comment block is for PHPDocumentor
/**
 * WoW Roster X - WoW Roster for Xoops
 *
 *
 *
 * @author Mike DeShane (mdeshane@pkcomp.net)
 * @copyright 2006 Mike DeShane, US
 */

/*
 * Definitions in this file conform to the Xoops standard for the modinfo.php file
 */

/**
 * The name of this module
 */
define('_MI_WRX_NAME', 'WoW Roster X');

/**
 *  A brief description of this module
 */
define('_MI_WRX_DESC', 'WoW Roster for Xoops');

/**#@+
 * Configuration item names and descriptions
 */

/**#@-*/

/**#@+
 * User menu names
 */
define('_MI_WRX_UMNAME0', 'Roster');
define('_MI_WRX_UMNAME1', 'Guild Info');
define('_MI_WRX_UMNAME2', 'Player Stats');
define('_MI_WRX_UMNAME3', 'Professions');
define('_MI_WRX_UMNAME4', 'Guild Bank');
define('_MI_WRX_UMNAME5', 'PVP Stats');
define('_MI_WRX_UMNAME6', 'Honor Stats');
define('_MI_WRX_UMNAME7', 'Member Log');
define('_MI_WRX_UMNAME8', 'Instance Keys');
define('_MI_WRX_UMNAME9', 'Profile Updater');
define('_MI_WRX_UMNAME10', 'Search');
define('_MI_WRX_UMNAME11', 'Quest Search');
define('_MI_WRX_UMNAME12', 'Add-Ons');

/**#@-*/

/**#@+
 * Block names and descriptions
 */
define('_MI_WRX_BLKNAME0', 'MOTD');
define('_MI_WRX_BLKDESC0', 'Guild Message of the Day');
define('_MI_WRX_BLKNAME1', 'Realm Status');
define('_MI_WRX_BLKDESC1', 'Displays the status of our realm');

/**#@-*/
/*
 * This file was generated by XBS ModGen, (c) 2006 A Kitson, UK. See http://xoobs.net
 * ModGen is a Module Code Generator for the Xoops CMS.  See http://xoops.org
 */
